// src/theme.js

export const premiumStyles = {
  appContainer: {
    backgroundColor: '#050b14', 
    color: '#f5f5f5',
    fontFamily: "'Playfair Display', 'Didot', 'Georgia', serif",
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '10px 6%',
    backgroundColor: '#0a1128', 
    borderBottom: '1px solid #1a2638',
  },
  logoContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  logoImage: {
    height: '75px', 
    width: '75px',
    objectFit: 'contain',
    borderRadius: '50%',
  },
  logoText: {
    fontSize: '22px',
    letterSpacing: '4px',
    color: '#d4af37', 
    margin: 0,
    fontWeight: '700',
  },
  loginNavBtn: {
    backgroundColor: 'transparent',
    border: '1px solid #d4af37',
    color: '#d4af37',
    padding: '8px 20px',
    cursor: 'pointer',
    letterSpacing: '1px',
    transition: '0.3s',
  },
  userBadge: {
    color: '#d4af37',
    fontSize: '15px',
    fontStyle: 'italic',
  },
  heroWrapper: {
    position: 'relative',
    height: '60vh',
    overflow: 'hidden',
    width: '100%',
  },
  heroSlide: {
    height: '100%',
    width: '100%',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background-image 0.8s ease-in-out',
  },
  heroContent: {
    textAlign: 'center',
    padding: '0 20px',
  },
  tagline: {
    fontSize: '36px',
    fontStyle: 'italic', 
    color: '#fff',
    letterSpacing: '2px',
    textShadow: '2px 2px 10px rgba(0,0,0,0.8)',
    margin: 0,
    fontWeight: '300',
  },
  searchSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: '-40px',
    position: 'relative',
    zIndex: 10,
    padding: '0 20px',
    gap: '15px',
  },
  searchBar: {
    backgroundColor: '#0a1128',
    border: '1px solid #d4af37',
    borderRadius: '4px',
    display: 'flex',
    flexWrap: 'wrap',
    padding: '20px',
    gap: '20px',
    maxWidth: '1000px',
    width: '100%',
    boxShadow: '0px 10px 30px rgba(0,0,0,0.5)',
  },
  filterWrapper: {
    display: 'flex',
    gap: '15px',
    justifyContent: 'center',
    width: '100%',
    maxWidth: '1000px',
  },
  filterBtn: {
    backgroundColor: '#111b33',
    border: '1px solid #1a2638',
    color: '#ccc',
    padding: '8px 16px',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '13px',
    transition: 'all 0.3s ease',
  },
  filterBtnActive: {
    backgroundColor: '#d4af37',
    border: '1px solid #d4af37',
    color: '#0a1128',
    padding: '8px 16px',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 'bold',
    transition: 'all 0.3s ease',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    flex: '1 1 180px',
  },
  label: {
    fontSize: '12px',
    color: '#b3b3b3',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    marginBottom: '6px',
  },
  input: {
    backgroundColor: '#111b33',
    border: '1px solid #1a2638',
    color: '#fff',
    padding: '10px',
    borderRadius: '4px',
    outline: 'none',
    fontSize: '14px',
  },
  guestInputs: {
    display: 'flex',
    gap: '4px',
  },
  searchButton: {
    backgroundColor: '#d4af37',
    color: '#0a1128',
    border: 'none',
    padding: '0 35px',
    fontSize: '16px',
    fontWeight: 'bold',
    letterSpacing: '1px',
    cursor: 'pointer',
    borderRadius: '4px',
    alignSelf: 'flex-end',
    height: '42px',
    marginTop: '10px',
  },
  mainContent: {
    maxWidth: '1200px',
    margin: '40px auto 0 auto',
    padding: '0 20px',
    flex: 1, // Pushes footer to bottom
  },
  sectionTitle: {
    fontSize: '24px',
    color: '#d4af37',
    fontWeight: '400',
    letterSpacing: '1px',
    marginBottom: '25px',
  },
  noResults: {
    textAlign: 'center',
    color: '#888',
    fontStyle: 'italic',
    padding: '40px 0',
  },
  resultsGrid: {
    display: 'grid',

    gridTemplateColumns: 'repeat(3, 1fr)', 
    gap: '30px',
    width: '100%',
    marginTop: '20px',
  },
    
  
  hotelCard: {
    backgroundColor: '#0a1128',
    border: '1px solid #1a2638',
    borderRadius: '6px',
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    animation: 'fadeIn 0.5s ease-in-out',
  },
  cardImage: {
    width: '100%',
    height: '220px',
    objectFit: 'cover',
  },
  cardBody: {
    padding: '20px',
  },
  cardHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  hotelName: {
    fontSize: '18px',
    fontWeight: '500',
    margin: '0 0 5px 0',
    color: '#fff',
  },
  ratingBadge: {
    backgroundColor: 'rgba(212, 175, 55, 0.15)',
    color: '#d4af37',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: 'bold',
  },
  hotelLocation: {
    fontSize: '13px',
    color: '#aaa',
    margin: '0 0 15px 0',
  },
  hotelPrice: {
    fontSize: '18px',
    color: '#d4af37',
    fontWeight: '600',
    margin: '0 0 15px 0',
  },
  perNight: {
    fontSize: '12px',
    color: '#888',
    fontWeight: 'normal',
  },
  viewDetailsBtn: {
    width: '100%',
    backgroundColor: 'transparent',
    border: '1px solid #d4af37',
    color: '#d4af37',
    padding: '10px 0',
    cursor: 'pointer',
    borderRadius: '4px',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.85)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '20px',
    backdropFilter: 'blur(5px)', // Premium blur effect
  },
  modalContent: {
    backgroundColor: '#0a1128',
    border: '1px solid #d4af37',
    borderRadius: '8px',
    maxWidth: '700px',
    width: '100%',
    maxHeight: '90vh',
    overflowY: 'auto',
    position: 'relative',
    animation: 'scaleUp 0.3s ease-out',
  },
  closeModalBtn: {
    position: 'absolute',
    top: '15px',
    right: '15px',
    backgroundColor: 'rgba(0,0,0,0.6)',
    border: 'none',
    color: '#fff',
    fontSize: '18px',
    cursor: 'pointer',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    zIndex: 10,
  },
  modalImage: {
    width: '100%',
    height: '300px',
    objectFit: 'cover',
  },
  modalBody: {
    padding: '30px',
  },
  modalHotelName: {
    fontSize: '26px',
    color: '#fff',
    margin: 0,
  },
  modalRating: {
    fontSize: '18px',
    color: '#d4af37',
    fontWeight: 'bold',
  },
  modalDescription: {
    color: '#ccc',
    lineHeight: '1.6',
    fontSize: '15px',
    margin: '15px 0',
  },
  roomTypeInfo: {
    color: '#d4af37',
    fontSize: '14px',
  },
  divider: {
    border: 'none',
    borderTop: '1px solid #1a2638',
    margin: '20px 0',
  },
  bookingControls: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '25px',
    backgroundColor: '#111b33',
    padding: '15px',
    borderRadius: '6px',
  },
  counterSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  counterLabel: {
    fontSize: '13px',
    color: '#aaa',
  },
  counterInterface: {
    display: 'flex',
    alignItems: 'center',
    gap: '15px',
  },
  counterBtn: {
    width: '32px',
    height: '32px',
    backgroundColor: '#0a1128',
    border: '1px solid #d4af37',
    color: '#fff',
    fontSize: '18px',
    cursor: 'pointer',
    borderRadius: '4px',
  },
  counterValue: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#fff',
  },
  priceCalculation: {
    textAlign: 'right',
  },
  totalPriceLabel: {
    fontSize: '12px',
    color: '#aaa',
    margin: 0,
    textTransform: 'uppercase',
  },
  totalPriceValue: {
    fontSize: '24px',
    color: '#d4af37',
    fontWeight: '700',
    margin: '5px 0 0 0',
  },
  bookNowBtn: {
    width: '100%',
    backgroundColor: '#d4af37',
    color: '#0a1128',
    border: 'none',
    padding: '14px 0',
    fontSize: '16px',
    fontWeight: 'bold',
    letterSpacing: '1px',
    cursor: 'pointer',
    borderRadius: '4px',
  },
  successMessage: {
    backgroundColor: 'rgba(40, 167, 69, 0.15)',
    border: '1px solid #28a745',
    padding: '20px',
    borderRadius: '6px',
    textAlign: 'center',
    fontSize: '22px',
  },
  authModal: {
    backgroundColor: '#0a1128',
    border: '1px solid #d4af37',
    borderRadius: '8px',
    padding: '40px',
    maxWidth: '400px',
    width: '100%',
    textAlign: 'center',
    position: 'relative',
    animation: 'scaleUp 0.3s ease-out',
  },
  authTitle: {
    fontSize: '24px',
    color: '#d4af37',
    margin: '0 0 10px 0',
    letterSpacing: '1px',
  },
  authSubtitle: {
    fontSize: '14px',
    color: '#aaa',
    margin: '0 0 25px 0',
    lineHeight: '1.4',
  },
  authForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '15px',
  },
  authInput: {
    backgroundColor: '#111b33',
    border: '1px solid #1a2638',
    color: '#fff',
    padding: '12px',
    borderRadius: '4px',
    fontSize: '14px',
    outline: 'none',
  },
  authSubmitBtn: {
    backgroundColor: '#d4af37',
    color: '#0a1128',
    border: 'none',
    padding: '12px',
    fontSize: '15px',
    fontWeight: 'bold',
    cursor: 'pointer',
    borderRadius: '4px',
    marginTop: '5px',
  },
  // --- New Review Styles ---
  reviewsContainer: {
    marginTop: '20px',
  },
  reviewTitle: {
    fontSize: '16px',
    color: '#d4af37',
    marginBottom: '10px',
  },
  reviewItem: {
    backgroundColor: '#111b33',
    padding: '10px 15px',
    borderRadius: '4px',
    marginBottom: '8px',
    fontSize: '13px',
    borderLeft: '3px solid #d4af37',
  },
  // --- New Footer Styles ---
  footer: {
    backgroundColor: '#0a1128',
    borderTop: '1px solid #1a2638',
    padding: '30px 6%',
    marginTop: '60px',
    color: '#b3b3b3',
    fontSize: '14px',
  },
  footerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: '20px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  footerSection: {
    flex: '1 1 250px',
  },
  footerHeading: {
    color: '#d4af37',
    fontSize: '16px',
    marginBottom: '12px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  footerText: {
    margin: '5px 0',
    lineHeight: '1.5',
  },
  footerBottom: {
    textAlign: 'center',
    borderTop: '1px solid #1a2638',
    marginTop: '20px',
    paddingTop: '15px',
    fontSize: '12px',
    color: '#666',
    letterSpacing: '1px',
  }
};